version: "3.8"
services:
  runner:
    image: gitea/act_runner:0.2.13
    environment:
      CONFIG_FILE: /config.yaml
      GITEA_INSTANCE_URL: "--gitea-url--"
      GITEA_RUNNER_REGISTRATION_TOKEN: "--runner-token--"
      GITEA_RUNNER_NAME: "--runner-name--"
    volumes:
      - ./config.yaml:/config.yaml
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
